### PR TITLE
Fix timeout and retries

### PR DESCRIPTION
**Pull request by aarbi**
I merged the new code added to cloudflare official node client
I bumped the request timeout to 30s and set the "retries" got http client's option correctly

### CODE REVIEW

**Comment by patrick-webs** [comment]
@aarbi can you cherry-pick the change from https://github.com/websdotcom/node-cloudflare/commit/241f081c42b176ae51983bb4975362264535b378 over to this as well? It looks like currently we depend on a custom version built with that commit `git+https://github.com/websdotcom/node-cloudflare.git#241f081`

**Comment by patrick-webs** [comment]
LGTM, :shipit:  @aarbi . Can we make a branch with just https://github.com/websdotcom/node-cloudflare/pull/1/commits/41ac6885d4594bf890f94a53cf725ecfc37bba1f and submit it to upstream as a pull request as well?

**Comment by aarbi** [comment]
all right, there are small bug fixes in the diff in this PR, but in general we don't need the features added in it

**Comment by aarbi** [comment]
created: https://github.com/websdotcom/node-cloudflare/pull/2

**Comment by aarbi** [comment]
opened a PR in upstream: https://github.com/cloudflare/node-cloudflare/pull/88

**Pull request merged**
